# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               JXLS
tagline:             'Create Excel reports using templates'
#description:         'JXLS'
url:                 https://github.com/SoltauFintel/jxls
baseurl:             'https://soltaufintel.github.io/jxls/'
paginate:            5

# About/contact
author:
  name:              SoltauFintel
  url:               https://github.com/SoltauFintel

# Custom vars
version:             0.72.0
